//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SeguroMedicoMFC.rc
//
#define ID_BORRAR                       3
#define ID_NUEVO                        4
#define ID_B_RECLAMOS                   5
#define ID_B_FILTER                     5
#define ID_B_INS_RESPONSE               6
#define ID_B_INS_RESPONSE2              7
#define ID_B_INS_RESPONSE_NEW           7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SeguroMedicoMFCTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDR_INSResponseMFCTYPE          132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_MainView                    310
#define IDD_SpecialtyDlg                311
#define IDD_DoctorDlg                   312
#define IDD_PatientDlg                  313
#define IDD_MedicationDlg               314
#define IDD_ClaimDlg                    315
#define IDD_InvoiceDlg                  316
#define IDD_INSResponseDlg              317
#define IDD_m_INSResponseLineDlg        318
#define IDD_INSResponseView             319
#define IDD_DateCalculator              320
#define IDC_GRID_1                      1000
#define IDC_E_ID_SPECIALTY              1001
#define IDC_E_NOMBRE_SPECIALTY          1002
#define IDC_L_SPECIALTIES               1004
#define ID_APPLY                        1005
#define ID_CERRAR                       1006
#define IDC_E_ID_DOCTOR                 1007
#define ID_CALCULATE                    1007
#define IDC_E_PRIMER_NOMBRE             1008
#define ID_FILTER                       1008
#define IDC_E_APELLIDOS                 1009
#define IDC_CB_SPECIALIDADES            1010
#define IDC_L_DOCTORES                  1011
#define ID_APLICAR_DOCTOR               1012
#define ID_NEW_DOCTOR                   1013
#define ID_BORRAR_DOCTOR                1014
#define ID_EDIT_SPECIALTIES             1015
#define IDC_E_ID_PATIENT                1015
#define IDC_L_PACIENTES                 1016
#define ID_APLICAR_PACIENTE             1017
#define ID_NEW_PATIENT                  1018
#define ID_BORRAR_PATIENT               1019
#define IDC_E_ID_MEDICATION             1020
#define IDC_E_NOMBRE_MEDICATION         1021
#define IDC_L_MEDICATIONS               1022
#define IDC_E_ID_CLAIM                  1023
#define IDC_C_PATIENTS                  1024
#define IDC_C_DOCTORES                  1025
#define IDC_C_MEDICAMENTOS              1026
#define IDC_START_DATE                  1027
#define IDC_END_DATE                    1028
#define IDC_E_ASPROSE_CLAIM_NUMBER      1029
#define IDC_E_ASPROSE_CASE_NUMBER2      1030
#define IDC_E_ASPROSE_AMOUNT_PRESENTED  1031
#define IDC_E_INS_CLAIM_NUMBER          1032
#define IDC_R_FULL                      1033
#define IDC_R_PARTIAL                   1034
#define IDC_R_NONE                      1035
#define IDC_E_TOTAL_CLAIM_AMOUNT        1036
#define IDC_E_COMMENT                   1037
#define IDC_CLAIMS_GRID                 1038
#define IDC_FECHA_ENTREGADO             1040
#define IDC_L_CLAIM_LIST                1041
#define IDC_E_ID_INVOICE                1042
#define IDC_C_CLAIM_LIST                1043
#define IDC_E_NUMERO_FACTURA            1044
#define IDC_E_AMOUNT                    1045
#define IDC_R_CONSULTA                  1046
#define IDC_R_EXAMEN                    1047
#define IDC_R_MEDICATION                1048
#define IDC_R_THERAPY                   1049
#define IDC_R_PROCEDIMIENTO             1050
#define IDC_E_DESCRIPTION               1051
#define IDC_C_INS_RESPONSE              1052
#define IDC_L_INVOICES                  1053
#define IDC_E_ID_INSRESPONSE            1054
#define IDC_E_LIQUIDACION_NUM           1055
#define IDC_E_NUMERO_CASO               1056
#define IDC_E_TOTAL_BRUTO               1057
#define IDC_E_OTRAS_DEDUCCIONES         1058
#define IDC_E_COPAGOS                   1059
#define IDC_E_COASEGUROS                1060
#define IDC_E_DEDUCIBLE_ANUAL           1061
#define IDC_E_TOTAL_NETO                1062
#define IDC_E_RETENCION                 1063
#define IDC_E_TIPO_CAMBIO               1064
#define IDC_E_TOTAL_A_PAGAR             1065
#define IDC_E_COMENTARIOS               1066
#define IDC_L_INSRESPONSES_LIST         1067
#define IDC_GRID                        1069
#define IDC_E_ID                        1070
#define IDC_C_FKEY_INSRESPONSE          1071
#define IDC_C_FKEY_INVOICE              1072
#define IDC_E_MONTO_CUBIERTO            1073
#define IDC_E_MONTO_FACTURA             1074
#define IDC_E_MONTO_DEDUCCIONES         1075
#define IDC_E_MONTO_COPAGOS             1076
#define IDC_E_MONTO_COASEGUROS          1077
#define IDC_E_MONTO_DEDUCIBLE_ANUAL     1078
#define IDC_E_MONTO_A_PAGAR             1079
#define IDC_E_MONTO_CUBIERTO_P100       1080
#define IDC_E_FACTURA_CUBIERTO_P100     1081
#define IDC_L_INSRESPONSELINE           1082
#define IDC_D_DATE_RESPONSE             1083
#define IDC_E_MONTO_A_PAGAR_COLONES     1083
#define IDC_E_MONTO_FACTURA2            1084
#define IDC_E_FACTURA_NUM               1084
#define IDC_E_OTHER_SYSTEM_ID           1085
#define IDC_B_PATIENTS                  1086
#define IDC_B_DOCTORES                  1087
#define IDC_B_INS_RESPONSES             1087
#define IDC_B_MEDICATIONS               1088
#define IDC_B_INVOICES                  1088
#define IDC_FECHA_INICIO                1088
#define IDC_FECHA_FINAL                 1089
#define IDC_B_FILTER                    1090
#define IDC_C_LISTA_DOCTORES            1091
#define IDC_C_LISTA_PACIENTES           1092
#define IDC_C_FILTER_BY_DATES           1093
#define IDC_E_CLAIM_AMOUNT              1094
#define IDC_C_LISTA_MEDICAMENTOS        1094
#define IDC_GRID_2                      1095
#define IDC_B_FILTER_INSRESPONSES       1096
#define IDC_C_CLAIM_IDS                 1097
#define IDC_B_CLEAR_FILTERS             1098
#define IDC_B_REFRESH                   1099
#define IDC_GRID_VIEW_1                 1099
#define IDC_E_NUM_FACTURA               1100
#define IDC_GRID_VIEW_2                 1100
#define IDC_E_NUM_FACTURA2              1101
#define IDC_B_CREAR_REEMBOLSO           1101
#define IDC_B_REFRESH2                  1102
#define IDC_E_DESC                      1102
#define IDC_C_INS_RESPONSE_IDS          1103
#define IDC_E_CLAIM_AMOUNT2             1103
#define IDC_E_CLAIM_AMOUNT_LESS_THAN    1103
#define IDC_E_INSREPONSE_AMOUNT         1104
#define IDC_GRID_3                      1104
#define IDC_B_ADD_FACTURA               1105
#define IDC_E_NUM_FACTURA_PENDIENTE     1105
#define IDC_E_SUM_INVOICES_AMOUNTS      1106
#define IDC_B_FILTER_3                  1106
#define IDC_C_SENT                      1107
#define IDC_B_CLEAR_FILTERS2            1107
#define IDC_B_CLEAR_FILTERS_3           1107
#define IDC_EDIT1                       1108
#define IDC_E_PORCENTAJE_PAGADO         1108
#define IDC_E_WEEKS                     1108
#define IDC_B_SELECT_REEMBOLSO          1110
#define IDC_E_SUM_PAGOS                 1111
#define IDC_GRID_INSRESPONSE_LINES      1112
#define IDC_B_CREAR_INS_RESPONSE        1113
#define IDC_B_BRING_FROM_INSRESPONSE    1114
#define ID_UP                           1117
#define ID_FILE_SPECIALTYDLG            32771
#define ID_FILE_DOCTORDLG               32772
#define ID_FILE_PATIENTDLG              32773
#define ID_FILE_MEDICATIONDLG           32774
#define ID_FILE_CLAIMDLG                32775
#define ID_FILE_INVOICEDLG              32776
#define ID_FILE_INSRESPONSEDLG          32777
#define ID_FILE_INSRESPONSELINEDLG      32778
#define ID_FILE_DATECALCULATOR          32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
