//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ExpenseManagerSQLite.rc
//
#define ID_B_APLICAR_STATEMENT          3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ExpenseManagerSQLiteTYPE    130
#define ID_WINDOW_MANAGER               131
#define IDR_ExpenseManagerSQLiteTYPE2   132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_ConceptsAndAccounts         310
#define IDD_BancoDlg                    311
#define IDD_CuentaDlg                   312
#define IDD_TransaccionDlg              313
#define IDD_PaisesDlg                   314
#define IDD_DuenosDlg                   315
#define IDD_ConceptosDlg                316
#define IDD_StatementDlg                317
#define IDD_CategoryDlg                 318
#define IDC_L_CONCEPTOS                 1000
#define IDC_GRID                        1001
#define IDC_B_CONNECT                   1002
#define IDC_B_DISCONNECT                1003
#define IDC_E_ACCOUNT_NUMBER            1004
#define IDC_B_PAIS_ADD                  1005
#define IDC_B_READ_STATEMENTLINE        1006
#define IDC_B_LOAD_COMPOUND_DOC         1007
#define IDC_L_TRANSACTIONS              1008
#define IDC_L_CUENTAS                   1009
#define IDC_E_DUENO                     1010
#define IDC_E_PAIS                      1011
#define IDC_E_ACCOUNT_DESC              1014
#define IDC_E_BANCO                     1015
#define IDC_C_IS_TARJETA                1016
#define IDC_B_BANCO_ADD                 1017
#define IDC_B_DUENO_ADD                 1018
#define IDC_B_CUENTA_ADD                1019
#define IDC_B_DISCONNECT3               1020
#define IDC_B_DISCONNECT4               1021
#define IDC_E_UBICACION                 1022
#define IDC_E_DESCRIPCION               1023
#define IDC_L_PAISES                    1024
#define IDC_E_NOMBRE_BANCO              1024
#define IDC_L_DUENOS                    1025
#define IDC_C_PAIS                      1025
#define IDC_B_DISCONNECT7               1026
#define IDC_B_ADD_PAIS                  1026
#define IDC_L_BANCOS                    1027
#define IDC_B_DISCONNECT8               1028
#define IDC_E_ID_CUENTA                 1028
#define IDC_B_REMOVE_ACCOUNT            1028
#define IDC_E_CUENTA_PROPIA             1029
#define IDC_E_DESCRIPTION               1029
#define IDC_E_CUENTA_OTRA               1030
#define IDC_E_NUMERO                    1030
#define IDC_E_CONCEPTO                  1031
#define IDC_C_DUENO                     1031
#define IDC_E_LINE_DATE                 1032
#define IDC_B_ADD_DUENOS                1032
#define IDC_E_STMT_DATE                 1033
#define IDC_R_TARJETA                   1033
#define IDC_E_AMOUNT_LOCAL              1034
#define IDC_R_CUENTA_BANCARIA           1034
#define IDC_E_AMOUNT_DOLARES            1035
#define IDC_C_BANCOS                    1035
#define IDC_B_DESELECT_DUENOS           1036
#define IDC_B_ADD_BANCOS                1036
#define IDC_B_DESELECT_ACCOUNTS         1037
#define IDC_B_DESELECT_BANCOS           1038
#define IDC_C_ESTADO_CUENTA             1038
#define IDC_B_DESELECT_PAIS             1039
#define IDC_B_ADD_STATEMENT             1039
#define IDC_B_CONCEPTO                  1040
#define IDC_C_CATEGORIAS                1040
#define IDC_B_DESELECT_CONCEPTOS        1041
#define IDC_E_TRANSACCION               1041
#define IDC_B_REMOVE_STATEMENT          1042
#define IDC_DATE_TRANSACTION            1043
#define IDC_B_REMOVE_TRANSACTION        1043
#define IDC_C_CONCEPTO                  1045
#define IDC_B_ADD_CONCEPT               1046
#define IDC_C_OWN_ACCOUNT               1047
#define IDC_C_OTHER_ACCOUNT             1048
#define IDC_E_MONTO_COLONES             1049
#define IDC_E_MONTO_DOLARES             1050
#define IDC_E_ID_PAIS                   1050
#define IDC_E_NOMBRE_PAIS               1051
#define IDC_B_ADD_OTHER_ACCOUNT         1051
#define IDC_B_APLICAR_PAISES            1053
#define ID_B_BORRAR                     1054
#define IDC_B_APLICAR_BANCO             1055
#define IDC_B_APLICAR_CUENTA            1056
#define ID_B_BORRAR_CUENTA              1057
#define IDC_B_APPLY_OWNER               1058
#define ID_B_NUEVA_CUENTA               1058
#define IDC_E_NOMBRE                    1059
#define ID_B_BORRAR_OWNER               1061
#define IDC_C_ACCOUNT                   1062
#define IDC_E_NOMBRE_CONCEPTO           1063
#define IDC_B_ADD_ACCOUNT               1064
#define IDC_B_APLICAR_CONCEPTO          1065
#define IDC_L_TRANSACTION               1066
#define IDC_B_APLICAR_TRANSACTIONS      1067
#define IDC_DATETIMEPICKER_STATEMENT    1071
#define IDC_L_ESTADOS_DE_CUENTA         1072
#define ID_BORRAR_STATEMENT             1073
#define IDC_E_CATEGORIA                 1074
#define IDC_C_IS_REAL                   1075
#define IDC_L_CATEGORIAS                1076
#define IDC_B_APLICAR_CATEGORY          1077
#define IDC_B_UPDATE_BANCO              1078
#define IDC_B_UPDATE                    1079
#define IDC_B_UPDATE_STATEMENT          1080
#define IDC_B_UPDATE_CONCEPTO           1081
#define IDC_B_UPDATE_ACCOUNT            1082
#define IDC_B_UPDATE_OWNERS             1083
#define IDC_B_UPDATE_PAIS               1084
#define IDC_B_UPDATE_TRANSACTION        1085
#define IDC_B_SAVE_TO_DB                1086
#define IDC_E_ROW                       1087
#define IDC_L_STATEMENTS                1088
#define IDC_E_ID_CONCEPTO               1089
#define IDC_E_ID_BANCO                  1090
#define IDC_E_ID_CATEGORIA              1091
#define IDC_E_ID_OWNER                  1092
#define IDC_E_ID_STATEMENT              1093
#define ID_Menu                         32771
#define ID_FILE_CUENTADIALOG            32772
#define ID_FILE_TRANSACCIONDIALOG       32773
#define ID_FILE_BANCODIALOG             32774
#define ID_FILE_PAISDIALOG              32775
#define ID_FILE_DUE32776                32776
#define ID_FILE_OWNER                   32777
#define ID_FILE_CONCEPTOSDIALOG         32778
#define ID_FILE_STATEMENTDIALOG         32779
#define ID_FILE_CATEGORYDIALOG          32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        319
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           319
#endif
#endif
